public  class ArithmeticCalculations {
    public Integer addition(integer x, integer y) {
        Integer z = x +y;
        return z;
        //return yazanson baska hic bir zat yazylmaly dal

    }

    public Integer subtract(integer x, integer y ){
        Integer z= x-y;
        return z;
    }
    
    public Integer multiplication( integer a, integer b, integer m){
        Integer z= a*b*m;
        return z;
    } 

}
